import "./globals.css";

export const metadata = {
  title: "ARAM Organize Parties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Assets/Logo.svg" />
      </head>
      <body>{children}</body>
    </html>
  );
}
